### ISSUE TITLE
Attempting to join an H2O cloud that is no longer accepting new H2O nodes

### ISSUE THREAD

**Issue by gurumoorthy208524** [h2oai/sparkling-water#2748]
Currently we are setting up the manual mode of external backend for sparkling water(3.36.0.3-1-3.1) using k8 (by following the steps in this [doc](https://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/deployment/kubernetes.html#manual-mode-of-external-backend)). But only one replica of statefulset out of 3, is running. Remaining two are in CrashLoopBackOff state. On logs we are able to see the following error. How can I solve this issue?? 
`ERROR water.default: Attempting to join an H2O cloud that is no longer accepting new H2O nodes from h2o-stateful-set-1.h2o-service.sparkling-water.svc.cluster.local`

**Comment by mn-mikke** [comment]
Hi @gurumoorthy208524,
Try to create cluster stateful set with the following configuration:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: h2o-stateful-set
  namespace: default
spec:
  serviceName: h2o-service
  replicas: 2
  selector:
    matchLabels:
      app: h2o-k8s
  template:
    metadata:
      labels:
        app: h2o-k8s
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: h2o-k8s
          image: 'h2oai/sparkling-water-external-backend:3.36.0.3-1-3.1'
          resources:
            requests:
              memory: "4Gi"
          ports:
            - containerPort: 54321
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /kubernetes/isLeaderNode
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
          env:
          - name: H2O_KUBERNETES_SERVICE_DNS
            value: h2o-service.default.svc.cluster.local
          - name: H2O_NODE_LOOKUP_TIMEOUT
            value: '180'
          - name: H2O_NODE_EXPECTED_COUNT
            value: '2'
          - name: H2O_KUBERNETES_API_PORT
            value: '8081'
```

+ deploy h2o headless service
```
apiVersion: v1
kind: Service
metadata:
  name: h2o-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: h2o-k8s
  ports:
  - protocol: TCP
    port: 54321
```
